packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  cpu-features: true
  msgpackr-extract: true
  prisma: true
  ssh2: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - cpu-features
  - msgpackr-extract
  - prisma
  - ssh2
